	main = congress
# INCLUDES = input-matching-instanc.tex

all: $(main).pdf

$(main).pdf : $(main).tex vc.tex $(INCLUDES)
	while (pdflatex $(main) ; \
	grep -q "Rerun to get cross" $(main).log ) do true ; \
	done

vc.tex: .git/logs/HEAD
	echo "%%% This file is generated by Makefile." > vc.tex
	echo "%%% Do not edit this file!\n%%%" >> vc.tex
	git log -1 --format="format:\\gdef\\GITAbrHash{%h}\\gdef\\GITAuthorDate{%ad}\\gdef\\GITAuthorName{%an}" >> vc.tex
