#!/bin/bash

# arguments are somewhere/file.pdf

set -e

for pdfname in $*; do
    (
    filename="${pdfname##*/}"
    basename="${filename%.pdf}"
    dir="${pdfname%/*}"
    echo $dir $basename
    texfile="$dir/$basename.tex"
    ls "$texfile"  # cheap way to check existence
    cd "$dir"
    GITSTATUS=`git status --porcelain "$basename.tex"`
    echo "%%% This file is generated by Makefile." > vc.tex
    echo "%%% Do not edit this file!\n%%%" >> vc.tex
    git log -1 --format="format:\\gdef\\GITAbrHash{%h $GITSTATUS}\\gdef\\GITAuthorDate{%ad}\\gdef\\GITAuthorName{%an}" -- "$basename.tex"  >> vc.tex
#    echo "\\gdef\\GITAbrHash{XX}\\gdef\\GITAuthorDate{ad}\\gdef\\GITAuthorName{an}"  >> vc.tex
    while (pdflatex "$basename" ; grep -q "Rerun to get" $basename.log ) do true ; done;
    if [ -e ../../bitbucketLogin.sh ]; then
        . ../../bitbucketLogin.sh
        if [ -z "$GITSTATUS" ]; then
            echo uploading $basename
            curl -s -u $BITBUCKETLOGIN -X POST "https://api.bitbucket.org/2.0/repositories/rikj/bads-labs/downloads" -F files=@"$basename.pdf"
        #else
            #touch -m -r "$basename.tex" "$basename.pdf"
            #touch -A -01 "$basename.pdf"
        fi
    fi
    )
done
               
