#!/bin/bash

# arguments are somewhere/file.pdf

set -e

for pdfname in $*; do
    (
    filename="${pdfname##*/}"
    basename="${filename%.pdf}"
    dir="${pdfname%/*}"
    echo $dir $basename
    texfile="$dir/$basename.tex"
    ls "$texfile"  # cheap way to check existance
    cd "$dir"
    GITSTATUS=`git status --porcelain "$basename.tex"`
    echo $GITSTATUS
    echo "%%% This file is generated by Makefile." > vc.tex
    echo "%%% Do not edit this file!\n%%%" >> vc.tex
    git log -1 --format="format:\\gdef\\GITAbrHash{%h $GITSTATUS}\\gdef\\GITAuthorDate{%ad}\\gdef\\GITAuthorName{%an}" -- "$basename.tex"  >> vc.tex
    while (pdflatex "$basename" ; grep -q "Rerun to get cross" $basename.log ) do true ; done;
    )
done
               

